name: ganvis
dependencies: 
    - python=3.7
    - pytorch
    - librosa
    - click
    - requests
    - tqdm
    - ninja
    - imageio-ffmpeg=0.4.3
    - ffmpeg
    - pip
    - pip: 
      - pyspng
      - youtube_dl
channels:
    - conda-forge
