name: ganvis
dependencies: 
    - python=3.7
    - pytorch=1.7.1
    - librosa
    - click
    - requests
    - tqdm
    - ninja
    - imageio-ffmpeg=0.4.3
    - ffmpeg
    - pip
    - pip: 
      - pyspng
channels:
    - conda-forge
