name: ganvis
dependencies: 
    - python=3.7
    - tensorflow=2.*
    - numpy
    - librosa
    - ffmpeg
    - pip
    - pip: 
      - youtube_dl
      - tensorflow-hub
channels:
    - conda-forge
    - pytorch
